Repository andOTP/andOTP, pull requests merged in 2019-09, with the labels that each got.

#368 QR-Code -> QR code
  app/src/main/res/values-ca-rES/strings_main.xml
  app/src/main/res/values-fr-rFR/strings_main.xml
  app/src/main/res/values-it-rIT/strings_main.xml
  app/src/main/res/values-zh-rTW/strings_main.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#362 new thumbnail for Diaspora
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_diaspora.xml
Labels: enhancement, thumbnail

#357 Password/pin field extended with direct focus
  app/src/main/res/layout/content_authenticate.xml
Labels: bug

#350 Fix all tags only selecting visible tags
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
Labels: bug

#314 ensure the filterstate is correctly applied after onCreate and onRestore
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
Labels: bug

#371 White navbar in light theme
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: enhancement
