Repository andOTP/andOTP, pull requests merged in 2019-10, with the labels that each got.

#366 Instantly generate new code when showing hidden code for HOTP token
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
Labels: enhancement

#372 Fix #258: save and show issuer and label separately
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
  app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java
  app/src/main/res/layout/component_card.xml
  app/src/main/res/layout/dialog_manual_entry.xml
  app/src/main/res/menu/menu_popup.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#405 Update links to HTTPS
  README.md
Labels: enhancement

#391 Workaround: Hide otp card on screen off (#264)
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
Labels: bug

#417 Fixed black navigation bar for OxygenOS devices #408
  app/src/main/java/org/shadowice/flocke/andotp/Activities/ThemedActivity.java
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: bug

#409 Add OPNsense, LibreNMS and PIA Icons
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_librenms.xml
  app/src/main/res/drawable/thumb_opnsense.xml
  app/src/main/res/drawable/thumb_private_internet_access.xml
Labels: enhancement, thumbnail

#410 Implemented #311. OTP details will turn red if it's about to expire in 8 seconds.
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
  app/src/main/res/values/colors.xml
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#393 Implemented intent-filter to receive otpauth requests
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#397 Create an encrypted backup when ever a new entry is added
  app/src/main/java/org/shadowice/flocke/andotp/Activities/BackupActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/BackupHelper.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement
