Repository andOTP/andOTP, pull requests merged in 2020-06, with the labels that each got.

#571 Quick grammar fix in removal text, from "want do remove" to "want to …
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#570 Fixes #569 - Validate expected Integer input for the Digits and Perio…
  app/src/main/java/org/shadowice/flocke/andotp/Dialogs/ManualEntryDialog.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
Labels: enhancement

#576 #149 English String suggestions
  app/src/main/res/values/strings_auth.xml
  app/src/main/res/values/strings_intro.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#575 Add weclapp icon
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_weclapp.xml
Labels: enhancement, thumbnail

#582 #580 confirm password field visibility
  app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java
  app/src/main/res/layout/component_intro_authentication.xml
Labels: bug
