Repository andOTP/andOTP, pull requests merged in 2020-09, with the labels that each got.

#573 Additional icons - Part 5
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_autodns.xml
  app/src/main/res/drawable/thumb_clubhouse.xml
  app/src/main/res/drawable/thumb_diaspora.xml
  app/src/main/res/drawable/thumb_esea.xml
  app/src/main/res/drawable/thumb_friendica.xml
  app/src/main/res/drawable/thumb_gogs.xml
  app/src/main/res/drawable/thumb_infomaniak.xml
  app/src/main/res/drawable/thumb_ntppoolproject.xml
  app/src/main/res/drawable/thumb_openvpn.xml
  app/src/main/res/drawable/thumb_roundcube.xml
  app/src/main/res/drawable/thumb_ubnt.xml
Labels: enhancement, thumbnail

#608 Additional icons - Part 6
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_cointracker.xml
  app/src/main/res/drawable/thumb_cyon.xml
  app/src/main/res/drawable/thumb_g2a.xml
  app/src/main/res/drawable/thumb_galaxus.xml
  app/src/main/res/drawable/thumb_mintos.xml
  app/src/main/res/drawable/thumb_noyb.xml
  app/src/main/res/drawable/thumb_qnap.xml
  app/src/main/res/drawable/thumb_wordfence.xml
Labels: enhancement, thumbnail

#641 #638 - Convert all password views with confirmation field to share toggle state
  app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Dialogs/PasswordEntryDialog.java
  app/src/main/java/org/shadowice/flocke/andotp/Preferences/CredentialsPreference.java
  app/src/main/java/org/shadowice/flocke/andotp/Preferences/PasswordEncryptedPreference.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/ConfirmedPasswordTransformationHelper.java
  app/src/main/res/layout/component_authentication.xml
  app/src/main/res/layout/component_password.xml
  app/src/main/res/layout/content_authenticate.xml
  app/src/main/res/layout/dialog_password_entry.xml
Labels: enhancement

#640 #639 Shared Preference NPE Fix
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
Labels: bug

#634 #631 - Fix NPE from invalid adapter position
  app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
Labels: bug
