Repository andOTP/andOTP, pull requests merged in 2020-02, with the labels that each got.

#420 Some more icons (IBM, Docker, 1and1)
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_1and1.xml
  app/src/main/res/drawable/thumb_bitmex.xml
  app/src/main/res/drawable/thumb_docker.xml
  app/src/main/res/drawable/thumb_finnair.xml
  app/src/main/res/drawable/thumb_ibm.xml
Labels: enhancement, thumbnail

#421 Add more auto backup settings
  app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/BackupHelper.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#425 Added feature to scan qr code from image file #377
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/ScanQRCodeFromFile.java
  app/src/main/res/drawable/ic_image_white.xml
  app/src/main/res/menu/menu_fab.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#342 Enable android backup by default
  app/src/main/res/xml/preferences.xml
Labels: bug, enhancement

#426 #253 Remove whitespaces in secret when added manually
  app/src/main/java/org/shadowice/flocke/andotp/View/ManualEntryDialog.java
Labels: enhancement, maybe

#392 Implemented #373. Added code to move the activity to background after copy to clipboard is selected.
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#390 added ability to ask for reauthentification after device inactivity
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#467 Added 'Most Used' sort option #443
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#466 Add AirBNB, AirTable, AppVeyor, Denic, Drupal, Friendica, GMX, Gov.UK…
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_airbnb.xml
  app/src/main/res/drawable/thumb_airtable.xml
  app/src/main/res/drawable/thumb_appveyor.xml
  app/src/main/res/drawable/thumb_denic.xml
  app/src/main/res/drawable/thumb_drupal.xml
  app/src/main/res/drawable/thumb_firefox.xml
  app/src/main/res/drawable/thumb_friendica.xml
  app/src/main/res/drawable/thumb_gmx.xml
  app/src/main/res/drawable/thumb_govuk.xml
  app/src/main/res/drawable/thumb_mailru.xml
Labels: enhancement, thumbnail
