Repository andOTP/andOTP, pull requests merged in 2021-03, with the labels that each got.

#758 Added option to hide issuer label #678
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntryViewHolder.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#772 Added slashed font to differentiate between zero and alphabet O in secret textbox #665
  README.md
  app/src/main/res/font/droid_sans_mono_slashed.ttf
  app/src/main/res/layout/dialog_manual_entry.xml
  app/src/main/res/values/aboutlibraries_definitions.xml
Labels: enhancement

#709 EntryThumbnail: Add Terraform Cloud thumb
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_terraform_cloud.xml
Labels: enhancement, thumbnail

#687 Use an thumbnail if its name appears as a word in the TOTP issuer field
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
Labels: enhancement

#771 Added password length check while creating backups #770
  app/src/main/java/org/shadowice/flocke/andotp/Dialogs/PasswordEntryDialog.java
  app/src/main/java/org/shadowice/flocke/andotp/Preferences/CredentialsPreference.java
  app/src/main/res/layout/component_authentication.xml
  app/src/main/res/layout/dialog_password_entry.xml
Labels: bug

#719 Update tooling
  .travis.yml
  app/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#742 [Thumbnail] Bitwarden Update
  app/src/main/res/drawable/thumb_bitwarden.xml
Labels: enhancement, thumbnail

#418 Added auto theme selection for Android 10 devices
  app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Activities/SettingsActivity.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Settings.java
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_settings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#617 This implements MOTP support
  app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java
  app/src/main/java/org/shadowice/flocke/andotp/Dialogs/ManualEntryDialog.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/TokenCalculator.java
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/UIHelper.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/res/layout/component_card_compact.xml
  app/src/main/res/layout/component_card_default.xml
  app/src/main/res/layout/component_card_full.xml
  app/src/main/res/menu/menu_popup.xml
  app/src/main/res/values/strings_main.xml
Labels: enhancement

#782 Additional icons - Part 9
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/EntryThumbnail.java
  app/src/main/res/drawable/thumb_1blu.xml
  app/src/main/res/drawable/thumb_archlinux.xml
  app/src/main/res/drawable/thumb_box.xml
  app/src/main/res/drawable/thumb_charles_schwab.xml
  app/src/main/res/drawable/thumb_circleci.xml
  app/src/main/res/drawable/thumb_cisco.xml
  app/src/main/res/drawable/thumb_cloudinary.xml
  app/src/main/res/drawable/thumb_ctemplar.xml
  app/src/main/res/drawable/thumb_directus.xml
  app/src/main/res/drawable/thumb_ftx.xml
  app/src/main/res/drawable/thumb_gandi.xml
  app/src/main/res/drawable/thumb_grammarly.xml
  app/src/main/res/drawable/thumb_improvmx.xml
  app/src/main/res/drawable/thumb_migadu.xml
  app/src/main/res/drawable/thumb_migros.xml
  app/src/main/res/drawable/thumb_namesilo.xml
  app/src/main/res/drawable/thumb_netcup.xml
  app/src/main/res/drawable/thumb_nexusmods.xml
  app/src/main/res/drawable/thumb_nvidia.xml
  app/src/main/res/drawable/thumb_onshape.xml
  app/src/main/res/drawable/thumb_opera.xml
  app/src/main/res/drawable/thumb_paywithprivacy.xml
  app/src/main/res/drawable/thumb_poeditor.xml
  app/src/main/res/drawable/thumb_porkbun.xml
  app/src/main/res/drawable/thumb_privacy.xml
  app/src/main/res/drawable/thumb_razer.xml
  app/src/main/res/drawable/thumb_stack.xml
  app/src/main/res/drawable/thumb_ultimaker.xml
  app/src/main/res/drawable/thumb_vmware.xml
  app/src/main/res/drawable/thumb_yoyogames.xml
Labels: enhancement, thumbnail

#792 fix QR code not found in image file
  app/build.gradle
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/ScanQRCodeFromFile.java
Labels: bug

#693 Add the feature to share the current OTP via an Intent
  app/src/main/java/org/shadowice/flocke/andotp/Utilities/Constants.java
  app/src/main/java/org/shadowice/flocke/andotp/View/EntriesCardAdapter.java
  app/src/main/res/menu/menu_popup.xml
  app/src/main/res/values-de/strings_main.xml
  app/src/main/res/values-de/strings_settings.xml
  app/src/main/res/values/settings.xml
  app/src/main/res/values/strings_main.xml
  app/src/main/res/values/strings_settings.xml
Labels: enhancement
